version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: echo "CircleCI Server Run"
workflows:
  build-workflow:
    jobs:
      - build

